---
- name: Install docker
  hosts: docker
  become: true

  tasks:
    - name: Install docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: true

#
#- name: Install InfluxDB key
#  get_url:
#    url:  https://repos.influxdata.com/influxdb.key
#    dest: /etc/apt/trusted.gpg.d/influxdb.asc
#
#- name:  Add InfluxDB repository
#  apt_repository:
#    repo:  "deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.asc] https://repos.influxdata.com/debian stable main"
#    state: present
#    update_cache: yes


    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        #keyring: /etc/apt/keyrings/docker.asc
        keyring: /etc/apt/trusted.gpg.d/docker.asc
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename | lower }} stable
        filename: docker
        state: present

    - name: Install docker engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-scan-plugin
          - docker-compose-plugin
        update_cache: true

# usermod -aG docker $USER 
    - name: add current user to group docker
      ansible.builtin.user:
        name: "{{ ansible_user }}" #alex
        groups: docker
        append: true

